# Generated by Django 4.1.3 on 2022-12-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('accountholder_name', models.CharField(max_length=20)),
                ('ifsc', models.BigIntegerField()),
                ('branch', models.CharField(max_length=25)),
                ('account_number', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
